---
info:
  scm-url: "@scm.url@"
  build-url: "http://travis-ci.org/@env.TRAVIS_REPO_SLUG@/builds/@env.TRAVIS_BUILD_ID@"
  stage: test

logging:
  file: "target/boot-admin.log"

management:
  context-path: "/actuator"
server:
  port: 8080
spring:
  application:
    name: "spring-boot-admin"
  boot:
    admin:
      url: http://localhost:8080
#      context-path: /metrics
  profiles:
    active:
      - secure

---
spring:
  profiles: insecure

management:
  security:
    enabled: false

security:
  basic:
    enabled: false

---
spring:
  profiles: secure
  boot:
    admin:
      username: "${security.user.name}"       #These two are needed so that the client
      password: "${security.user.password}"   #can register at the protected server api
      client:
        metadata:
          user.name: "${security.user.name}"          #These two are needed so that the server
          user.password:  "${security.user.password}" #can access the proteceted client endpoints

security:
  user:
    name: user
    password: pass


